"""add enrollments

Revision ID: a26ca6410359
Revises: 2dcc66472ff5
Create Date: 2026-01-04 17:35:34.127710

"""
from alembic import op
import sqlalchemy as sa



revision = 'a26ca6410359'
down_revision = '2dcc66472ff5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
