"""add enrollments

Revision ID: dd5c20fdaa44
Revises: 065951fddd4b
Create Date: 2026-01-04 18:14:30.764787

"""
from alembic import op
import sqlalchemy as sa



revision = 'dd5c20fdaa44'
down_revision = '065951fddd4b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
